# Generated by Django 5.2 on 2025-04-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopy9250', '0002_formdata_delete_appdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='content',
        ),
        migrations.AddField(
            model_name='formdata',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='formdata',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
