# Generated by Django 5.2 on 2025-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopy9250', '0003_remove_formdata_content_formdata_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='additional_inputs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
